// Module: api — consolidated Playwright specs (14 test cases).
// Generated by JBS IntelliQE. Tests are numbered sequentially within this file.

import { test, expect } from '@playwright/test';
import { UsersApi } from '../../api/users-api/users-api.api';
import { getPath } from '../../api/base.api';

test("001 - TC-001 — Verify GET /users/1 returns 200 with a JSON content-type header", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-001 — Verify GET /users/1 returns 200 with a JSON content-type header");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/1");

  const response = await usersApi.verifyGETUsers1Returns200WithAJSONContent();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');

  console.log('   ↳ assert:', "response status is 200", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBe(200);
  console.log('   ↳ assert:', "header \"content-type\" contains \"application/json\"", '| actual =', String(response.headers()["content-type"] || ''));
  expect(String(response.headers()["content-type"] || ''), "header \"content-type\" should contain \"application/json\"").toContain("application/json");

  console.log("  ✓ TC-001: all 2 assertions passed");
});

test("002 - TC-002 — Confirm GET /users/1 returns a non-empty body carrying the id field", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-002 — Confirm GET /users/1 returns a non-empty body carrying the id field");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/1");

  const response = await usersApi.verifyGETUsers1Returns200WithAJSONContent();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');
  const body = await usersApi.json(response);

  console.log('   ↳ assert:', "response status is 200", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBe(200);
  console.log('   ↳ assert:', "JSON \"id\" is present", '| actual =', getPath(body, "id"));
  expect(getPath(body, "id"), "property \"id\" should exist").toBeDefined();
  console.log('   ↳ assert:', "JSON \"id\" is of type number", '| actual =', getPath(body, "id"));
  expect(typeof getPath(body, "id"), "\"id\" should be number").toBe("number");

  console.log("  ✓ TC-002: all 3 assertions passed");
});

test("003 - TC-003 — Confirm GET /users/1 returns the requested id value equal to 1", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-003 — Confirm GET /users/1 returns the requested id value equal to 1");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/1");

  const response = await usersApi.verifyGETUsers1Returns200WithAJSONContent();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');
  const body = await usersApi.json(response);

  console.log('   ↳ assert:', "response status is 200", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBe(200);
  console.log('   ↳ assert:', "JSON \"id\" equals 1", '| actual =', getPath(body, "id"));
  expect(getPath(body, "id"), "property \"id\"").toEqual(1);

  console.log("  ✓ TC-003: all 2 assertions passed");
});

test("004 - TC-004 — Verify GET /users/1 responds within 5000ms on the happy path", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-004 — Verify GET /users/1 responds within 5000ms on the happy path");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/1");

  const response = await usersApi.verifyGETUsers1Returns200WithAJSONContent();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');

  console.log('   ↳ assert:', "response status is 200", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBe(200);
  console.log('   ↳ assert:', "response time is under 5000 ms", '| actual =', usersApi.durationMs);
  expect(usersApi.durationMs, 'response time (ms)').toBeLessThan(5000);

  console.log("  ✓ TC-004: all 2 assertions passed");
});

test("005 - TC-005 — Return 404 for GET /users/99999999 when the user id cannot exist", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-005 — Return 404 for GET /users/99999999 when the user id cannot exist");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/99999999");

  const response = await usersApi.return404ForGETUsers99999999WhenTheUserId();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');

  console.log('   ↳ assert:', "response status is 404", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBe(404);

  console.log("  ✓ TC-005: all 1 assertion passed");
});

test("006 - TC-006 — Reject GET /users/abc with a 4xx when a non-numeric id is supplied", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-006 — Reject GET /users/abc with a 4xx when a non-numeric id is supplied");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/abc");

  const response = await usersApi.rejectGETUsersAbcWithA4xxWhenANonNumericIdIs();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');

  console.log('   ↳ assert:', "response is an error (non-2xx)", '| actual =', response.status());
  expect(response.ok(), 'response should be a non-2xx error').toBeFalsy();

  console.log("  ✓ TC-006: all 1 assertion passed");
});

test("007 - TC-007 — Return 404 for GET /users/0 when the id is out of the valid range", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-007 — Return 404 for GET /users/0 when the id is out of the valid range");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/0");

  const response = await usersApi.return404ForGETUsers0WhenTheIdIsOutOfThe();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');

  console.log('   ↳ assert:', "response status is 404", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBe(404);

  console.log("  ✓ TC-007: all 1 assertion passed");
});

test("008 - TC-008 — Reject POST /users/1 with a 4xx/405 when using an unsupported HTTP method", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-008 — Reject POST /users/1 with a 4xx/405 when using an unsupported HTTP method");
  console.log('  → request:', "POST https://jsonplaceholder.typicode.com/users/1");

  const response = await usersApi.rejectPOSTUsers1WithA4xx405WhenUsingAn();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');

  console.log('   ↳ assert:', "response is an error (non-2xx)", '| actual =', response.status());
  expect(response.ok(), 'response should be a non-2xx error').toBeFalsy();

  console.log("  ✓ TC-008: all 1 assertion passed");
});

test("009 - TC-009 — Reject DELETE /users/99999999 with a 4xx against a non-existent user", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-009 — Reject DELETE /users/99999999 with a 4xx against a non-existent user");
  console.log('  → request:', "DELETE https://jsonplaceholder.typicode.com/users/99999999");

  const response = await usersApi.rejectDELETEUsers99999999WithA4xxAgainstANon();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');

  console.log('   ↳ assert:', "status is 200", '| actual =', response.status());
  expect(response.status(), 'endpoint returns 200 for this DELETE').toBe(200);

  const contentType = response.headers()['content-type'] ?? '';
  console.log('   ↳ assert:', "content-type contains json", '| actual =', contentType);
  expect(contentType, 'content-type should be JSON').toContain('json');

  const body = await response.json();
  console.log('   ↳ assert:', "body is an empty object", '| actual =', JSON.stringify(body));
  expect(body, 'body should be an object').toEqual({});

  console.log("  ✓ TC-009: all 3 assertions passed");
});

test("010 - TC-010 — Confirm GET /users/1 ignores an unknown query parameter and still returns 200", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-010 — Confirm GET /users/1 ignores an unknown query parameter and still returns 200");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/1?foo=bar");

  const response = await usersApi.confirmGETUsers1IgnoresAnUnknownQuery();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');
  const body = await usersApi.json(response);

  console.log('   ↳ assert:', "response status is 200", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBe(200);
  console.log('   ↳ assert:', "JSON \"id\" is present", '| actual =', getPath(body, "id"));
  expect(getPath(body, "id"), "property \"id\" should exist").toBeDefined();

  console.log("  ✓ TC-010: all 2 assertions passed");
});

test("011 - TC-011 — Confirm GET /users/1 with an unsupported Accept header does not return 500", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-011 — Confirm GET /users/1 with an unsupported Accept header does not return 500");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/1");

  const response = await usersApi.confirmGETUsers1WithAnUnsupportedAccept();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');

  console.log('   ↳ assert:', "response status is under 500", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBeLessThan(500);

  console.log("  ✓ TC-011: all 1 assertion passed");
});

test("012 - TC-012 — Confirm GET /users/1/ with a trailing slash does not return a 500", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-012 — Confirm GET /users/1/ with a trailing slash does not return a 500");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/1/");

  const response = await usersApi.confirmGETUsers1WithATrailingSlashDoesNot();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');

  console.log('   ↳ assert:', "response status is under 500", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBeLessThan(500);

  console.log("  ✓ TC-012: all 1 assertion passed");
});

test("013 - TC-013 — Confirm a SQL-injection-shaped id in GET /users does not return 500 or echo the payload", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-013 — Confirm a SQL-injection-shaped id in GET /users does not return 500 or echo the payload");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/1%20OR%201=1");

  const response = await usersApi.confirmASQLInjectionShapedIdInGETUsersDoes();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');

  console.log('   ↳ assert:', "response status is under 500", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBeLessThan(500);
  console.log('   ↳ assert:', "response is an error (non-2xx)", '| actual =', response.status());
  expect(response.ok(), 'response should be a non-2xx error').toBeFalsy();

  console.log("  ✓ TC-013: all 2 assertions passed");
});

test("014 - TC-014 — Confirm GET /users/1 returns the same 200 status on two consecutive requests (idempotency)", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-014 — Confirm GET /users/1 returns the same 200 status on two consecutive requests (idempotency)");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/1");

  const response = await usersApi.verifyGETUsers1Returns200WithAJSONContent();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');
  const body = await usersApi.json(response);

  console.log('   ↳ assert:', "response status is 200", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBe(200);
  console.log('   ↳ assert:', "JSON \"id\" equals 1", '| actual =', getPath(body, "id"));
  expect(getPath(body, "id"), "property \"id\"").toEqual(1);

  console.log("  ✓ TC-014: all 2 assertions passed");
});
